### ISSUE TITLE
RPM configuration files cause httpd to fail to start on Centos7

### ISSUE THREAD

**Issue by alexrawcliffe** [bbc/nmos-reverse-proxy#2]
The RPM package's httpd configuration files are causing httpd to fail to start with the follow error:

```Syntax error on line 5 of /etc/httpd/conf.d/nmos-reverseproxy-common.conf: Could not open config directory /etc/httpd/conf.d/nmos-apis: No such file or directory```

A directory listing of /etc/httpd/conf.d/ shows the nmos-apis/ directory has not been created.
ips-apis/ does exist (both are referred to in the base configuration file at https://github.com/bbc/nmos-reverse-proxy/blob/master/rpm/nmos-reverseproxy-common.conf)

**Comment by simonrankine** [comment]
Fixed in e1908609071fc5db75689f67be1f4413d7aba621
